### ISSUE TITLE
create "proof of concept" for looped pipeline that explicitly uses user_params 

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#106]
toy example of main script that iterates over function names in json for discussion

**Comment by DMRoberts** [comment]
I created a pretty simple example, since it contains multiple files I added it as a Gist here: 

https://gist.github.com/DMRoberts/2b2b47505058013865fb8594cfdbf497

It produces JSON as output, which looks like:

`'{"pipeline_func_three": 1560, "pipeline_func_two": 2.0, "pipeline_func_one": 59}'`

In my example each function returns a dict with the function name as a key, and the values that belong to the output of that function as a series of key, value pairs. Another option would be to just return the key, value pairs from each pipeline function, and label each as they are returned. In that case the function name could be changed without also needing to update the label in the dict that is returned from that function.

For example for an arbitrary example, instead of a function returning:

` {'channel_rejection': {'rejected_channels': ['Cz, Pz'], 'Threshold': 50}}
` 
 It would just return:
 
`  {'rejected_channels': ['Cz, Pz'], 'Threshold': 50}
`  

  And the main script, knowing that is just called 'channel_rejection' would label the output appropriately.

**Comment by yanbin-niu** [comment]
@DMRoberts  very smart idea! 

Two quick questions:
1. Isn’t dict a non-sequential data type? How can we control the sequence of the pipeline? (I just googled it and it seems not a big deal or even an issue)
2. Most functions actually need raw to be passed to. I think it may not be a problem, if we add a separate step to read in the path from user_params, use feature-io to get the raw and pass the raw to each function. But, what if, like @Jonhas said, feature-segment will return two values and one of them will be passed to next function (interpolate). So, is there a way to do some “special” implementing for some special functions? (We might, of course, put those two steps together?)

I am just trying to understand your script. Excuse me if I misunderstood something!

**Comment by yanbin-niu** [comment]
Just realize that my description is not very clear.
1. I mean "a separate step" is a step outside the loop, then we also need to remove this item from the user_params.
2. I mean "some special functions " are a situation in which the functions return different amount of values.

**Comment by yanbin-niu** [comment]
Another thing might need to be considered: we actually have a bigger loop - looping through all tasks. Specially, our example data have several tasks. That is, we need a function in main (maybe call a function from feature-io) to loop through all the task names ( or even with combination with different runs) that user_params provides. In each loop, we need the task name in that loop to name the files that save the raw in each step and output Jason file. Sorry if I complicate the thing.

**Comment by F-said** [comment]
@yanbin-niu @DMRoberts we should plan out how this pipeline will run on each task within our BIDS data. I'll make some preliminary plans and tag you in for feedback.

We will also need to consider that eventually, this pipeline will run in parallel on each task on the computer cluster.

**Comment by F-said** [comment]
Expanded on @DMRoberts example gist with some completed pipeline steps to see how integration will go: 

https://gist.github.com/F-said/76b7b3c14e4364e6075c1378b459c504

Added in raw to each function call as described in the pipeline, and separated out the loading of data into files.

Some observations on pipeline integration:

## Standardization Requirements 

* Pipeline function parameters: 
    * Potential format: first data, then *explicit* parameters 
    `pipeline_step(data, user_param1, user_param2, user_param3)`
    
    That way the pipeline can call `pipeline_step(raw, **user_params)` w/o any error
    
* Pipeline function return values: 
     * Potential format: return only `output_dict` to satisfy reqs of pipeline plan
     `return output_dict`

## Challenges
1. As @yanbin-niu pointed out final_reject takes in both raw & epochs. This violates the pipeline loop expected parameter list `(raw, **user_params)`. 
2. Relatedly, the `segment` function returns `epochs` since the pipeline needs to pass it to `final_reject(raw, epochs, **params**)`, which violates the `output_preprocess` function which writes out all output_dicts to a JSON file. 
3. JSON module cannot write `mne.io.Raw.info` or `mne.Epochs.info` to the output file since they are non-serializable. 

## And their potential solutions

1. (1 & 2 tied together) final_reject/segment issue various solutions: 
    1. Remove `final_reject` as pipeline step from JSON file and make it called inside of `segment`
        - **Pros**:
            - Segment won't have to return epochs
            - main pipeline won't see final_reject 
        - **Cons**:
            - final_reject annotations will have to be inserted inside of segment annotations
            - Unexpected behavior from segment 
    2. Refactor `final_rej` to only take in epochs
        - **Pros**:
            - parameter list will be all same size, so the parameter list might not be violated
        - **Cons**:
            - segment still needs to return epochs 
            - How do we know when to pass epochs and not raw?
    3. Make `segment` function assign `epochs` data to `final_reject` user_params 
        - **Pros**:
            - Segment won't have to return epochs
            - main pipeline will have no issue with final_reject as **user_params will satisfy the parameter list of `final_reject(raw, epochs, tmin, tmax)`
        - **Cons**:
            - giving segment additional responsibility of writing to user_params
 
@NDCLab/base-eeg-team Insight and feedback on this would greatly be appreciated. 
    
@georgebuzzell This approach of looping over the JSON file is a great way to abstract the gritty details. It's almost like an informal [domain-specific-language](https://en.wikipedia.org/wiki/Domain-specific_language) for EEG researchers looking to make clean data. 

Will make additional issues for required changes if we decide to move forward. Otherwise, will make issues for making an explicit pipeline.

**Comment by DMRoberts** [comment]
@yanbin-niu On your question:

> Isn’t dict a non-sequential data type? How can we control the sequence of the pipeline? (I just googled it and it seems not a big deal or even an issue)

This is a good point, I believe that the dict type was originally not ordered in Python, but has changed to be ordered as of Python 3.7. Similarly the json module now imports and exports dicts in the same order as they occur in the json file, which previously wasn't necessarily the case. Since we'll be using Python >= 3.7 with MNE I think we should be ok there.

One other potential issue may be related to whether json itself is strictly ordered. For example someone used a different tool to open the user_params json file, edit the values, and export it to json, would the keys be guarantees to be in the original order? I'm not sure at the moment.

@yanbin-niu On your other comments:

You're right that we would also need an outer loop here, to iterate over tasks, or over participants within the dataset.

I think the loading of data would probably done outside of the pipeline 'loop', as in the example @F-said posted - basically the path of the BIDS dataset is in a different part of the JSON user_params, which is loaded and then provided to the first step of the pipeline.

I might have to look at some of the existing pipeline steps / features in more detail along with @F-said 's post to see if they could all conform to the same format / API. I had been imagining each step would take a single EEG object and parameters, and either return:

1) The output values ( modifying the EEG object provided to the function in-place )
2) The output values and a modified EEG object

**Comment by yanbin-niu** [comment]
@F-said 


> we should plan out how this pipeline will run on each task within our BIDS data. I'll make some preliminary plans and tag you in for feedback.
> 
> We will also need to consider that eventually, this pipeline will run in parallel on each task on the computer cluster.

Agree. I was thinking about the file names for eeg data after each processing step (#95 ) and output.json. So, no matter we currently run on one task or loop over all tasks, we need to know the task name for the naming of the files. Specifically, for output.json, I do not think it is a problem, since writing happens in the main and we will find out a way to get the task name. But for the naming of eeg data after each processing step, writing happens within each feature. One of solutions would be sending back the data and write that in the main. I brought this up because it might impact @DMRoberts 's looping.

**Comment by yanbin-niu** [comment]
@DMRoberts 
1
For the dict issue, I actually tried your script and searched a little bit. As you said, it seems not an issue. Also,  json itself should be ordered. ( https://docs.python.org/3/library/json.html#encoders-and-decoders)

> Note This module’s encoders and decoders preserve input and output order by default. Order is only lost if the underlying containers are unordered.
> Prior to Python 3.7, dict was not guaranteed to be ordered, so inputs and outputs were typically scrambled unless collections.OrderedDict was specifically requested. Starting with Python 3.7, the regular dict became order preserving, so it is no longer necessary to specify collections.OrderedDict for JSON generation and parsing.

2
Agree - the raw data should be got outside the loop. So, the feature-io should also read from `user_params` dict to get something like participants, mapping of event codes to tasks (e.g., '90': 'RestingState', '91': 'SequenceLearning'....) etc., correct?

**Comment by georgebuzzell** [comment]
In response to @F-said 's comment above, I think the solution of combing final reject and segment together, such that segment calls final reject, would be a good solution. The reasoning here, is that you really shouldn't segment the data without running the final rejection, so, at least from a conceptual erg-preprocessing view, it is find to combine these two.

I also think making function return of dictionaries explicit is perfectly fine. I see now downside to here, really. Am I missing something?

As mentioned on Slack, I do think this approach is clever @DMRoberts and I very much appreciate the excellent additions by @F-said and @yanbin-niu . I am happy to devote some time to seeing how viable this is. However, I do want to keep the deadline of having a viable and working main pipeline plan by the meeting at 10 am this Friday (5/21). If we can get this plan working, then great! But if not, the back up will be to return to the original plan of having the main script call each function directly. If we need to switch back to that plan, then, I would very much like to move this optimized version of made that you all have proposed be shifted to being a primary focus of the next "release". I.e. we would get an initial pipeline working with a more simple version of the main script, then, once everything works, we would convert it to this optimized approach. Does that make sense? Agree? Thoughts/concerns?

@Jonhas @stevenwtolbert @SDOsmany

**Comment by F-said** [comment]
✅ Modified pipeline functions per feedback to standardize return values and passed values.
✅ Refactored functions after segment to omit the use of raw 

Looped pipeline works so far

Making PR requests for each function modified/documented and tagging each original author. Once pipeline & data functions are updated, and file/directory structure is set up, will make PR for main pipeline script into dev. 

✅ Modified UML diagram to express now that each function returns raw and each function after segment takes in epochs.

Making PR request for edited UML diagram

@georgebuzzell

**Comment by F-said** [comment]
closing and moving to main pipeline enhancement #118
