### ISSUE TITLE
BIDS & processed data 

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#238]
**Background**
While conforming preprocessed data to BIDS, the following hurdles have been encountered

- derivatives must be written as `.fif` or `_epo.fif`, even though original data is in `.vhdr`
- its recommended raw should not be preloaded (which derivatives are) when writing them using `mne_bids.write_raw()`
  - There is an option to write preloaded data, but then we lose the option to keep intermediate data the same as the original data (turns into BrainVision format)  
- function names do not abide by BIDS standards when tagging them in file names
- there is no standard for writing epochs in BIDS

which points to this piece of documentation

> BIDS was originally designed for unprocessed or minimally processed data. For this reason, by default, we prevent writing of preloaded data that may have been modified. Only use this option when absolutely necessary: for example, manually converting from file formats not supported by MNE or writing preprocessed derivatives. Be aware that these use cases are not fully supported.

**Defined as Done**
How should preprocessed data format be handled since BIDS does not fully support derivative use-cases?

- Make a standard and suggest directly to authors of BIDS?
- Make a BBIDS (Buzzell BIDS) for derivatives? 
- [this comment](https://mne.discourse.group/t/mne-bids-writing-files-only-works-if-data-are-unloaded/2480) suggests using `mne-python` after initial reading and writing

**Comment by georgebuzzell** [comment]
Per the discussion last week, the plan is as follows:

All derivative files (for the output of each step of the pipeline, and the final output) should all be written as FIF files with no additional meta data written. Naming conventions for these files should all follow the bids standard naming conventions.

within the bids data set (e.g., "cmi") there should be the following folders:

cmi/
->sourcedata/
--> (All the CMI data, directly copied from the s3 buckets, goes here)

->raw_data/
--> (All the bids formatted raw data goes here)

->derivatives/
-->pipeline_pyprep-eeg/

--->pyprep-eeg_intermediate/
---->sub-xx
----->ses-xx
------>eeg
-------> (all the .fif files output from each preprocessing step go here. Also, all the output_dict goes here only if the pipelines fails to run to the end; otherwise, the output_dict goes in the 'preprocessed' folder with the final fif file)

--->pyprep-eeg_preprocessed/
---->sub-xx
----->ses-xx
------>eeg
-------> (only the final .fif goes here.. Also, the output_dict goes here, unless the pipelines fails to run to the end; in which case the output_dict goes in the 'intermediate' folder alongside the intermediate fif files)

@DMRoberts, @F-said, @SDOsmany, @yanbin-niu Please take a look and let me know if you agree, or if you have any suggestions for improvement, or have any clarification questions.

PS we really need to come up with a name for this pipeline! I am just calling it "pyprep-eeg" for now...

**Comment by F-said** [comment]
Incorporated into #248 and closing

**Comment by yanbin-niu** [comment]
@georgebuzzell the structure looks great! The only thing I was thinking: will it be confused that the position of the output_dict depends on running the pipeline successfully or not? Or we can save the output_dict to the pyprep-eeg_preprocessed no matter pipeline is successful or not, but provide the error message in the output_dict. so that users can always find the output_dict  in a fixed place. Not sure whether this makes sense.
