### ISSUE TITLE
Standard_1020 montage results in error

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#340]
**Describe the bug**
Standard_1020 parameter results in following error in `set_montage()`. 
```
Invalid value for the 'montage' parameter.
```

**Expected behavior**
Standard_1020 should be an acceptable param.

**Comment by georgebuzzell** [comment]
@F-said @DMRoberts is this a new test that is driving this error?

**Comment by F-said** [comment]
@georgebuzzell No, just output from the function

**Comment by DMRoberts** [comment]
@F-said Do you get the error with the MNI data and `'GSN-HydroCel-129'` ?

'standard-1020' will generate an error with the MNI data because the channels aren't in the 10-20 locations. MNE will generate an error that the names don't match, I believe you just aren't seeing it at the moment because we had caught the MNE ValueError exceptions and inserted our 'invalid montage' exception instead. I believe removing those custom error messages and allowing the MNE errors to pass through will resolve that ambiguity.

But for example, try:

```
import mne
import mne_bids
from pathlib import Path

from scripts.preprocess import preprocess as pre

# load the data
bids_path = mne_bids.BIDSPath(subject='NDARAB793GL3', task='ContrastChangeBlock1', session='01', run='01', root=Path('CMI/rawdata/'), datatype='eeg')
raw = mne_bids.read_raw_bids(bids_path)

# this should work
raw = pre.set_montage(raw, 'GSN-HydroCel-129')

# this generates an error (the channel names don't match), though the error message isn't correct since we are catching all ValueErrors
raw = pre.set_montage(raw, 'standard_1020')

# you can see the actual error message by calling set_montage on the raw object, which is what our pre.set_montage function is doing internally
raw.set_montage('standard_1020')
```

**Comment by F-said** [comment]
Thanks @DMRoberts !

**Comment by F-said** [comment]
resolved, closing
