### ISSUE TITLE
Ica_raw empty epochs bug

### ISSUE THREAD

**Issue by F-said** [NDCLab/baseEEG#345]
**Describe the bug**
On certain tasks, running `ica_raw()` on tasks such as `ContrastChangeBlock1` and `ContrastChangeBlock2` result in an empty epochs error. 

**Expected behavior**
Ica_raw should process or skip. @georgebuzzell @yanbin-niu how should ica_raw move forward if it drops **all** epochs?

**Screenshots**
![image](https://user-images.githubusercontent.com/26397102/136257733-880864b8-5a60-45e5-bbe2-922455e6eccf.png)

**Comment by yanbin-niu** [comment]
@F-said do you mean epochs were dropped by the previous step or by itself? Or this data is resting state data( without event marker) ?

Did this runtime error throw by MNE? I guess we can catch it? Kind of similar to how we deal with other errors.

**Comment by F-said** [comment]
@yanbin-niu It seems like the epochs were dropped by the step itself. And yes it was thrown by MNE. 

It also seems to impact a wide range of tasks, will comment which tasks it impacts

**Comment by yanbin-niu** [comment]
@F-said Got it. So I was thinking this might be caused by trying to removing "noisy" epochs based on the amplitude at the prep-ica step. Do you think I can just catch this ICA error and raise an error, so you can catch it in the main loop and skip this participant?

@georgebuzzell what do you think about this?

**Comment by F-said** [comment]
@yanbin-niu Just rechecked! It was actually a bug within the *test* itself instead of ICA. NVMD!
