### ISSUE TITLE
Should we add the reference channel at the earlier stage or at the last step - re-reference

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#351]
I was wondering how we should properly deal with a situation in which the reference channel is not initially included in the raw data. I believe such situation exists, right? If so, should we add the reference channel back to the data at the earlier stage (while setting up the montage) or at the last step, namely re-reference?

@DMRoberts @georgebuzzell

**Comment by DMRoberts** [comment]
@yanbin-niu You're correct that sometimes the reference channel is included in the raw data, and sometimes it is not (because the values of the channel would all be 0). As far as I can tell, I don't think there is anything in the BIDS standard specifying that the data from reference channel should be included.

At the moment we are adding the reference channel to the data prior to re-referencing if it is specified by the user: https://github.com/NDCLab/pepper-pipeline/blob/1e87c5ae1274f2f15fc820d96415425ac9122e3d/scripts/preprocess/preprocess.py#L87

It would probably be better to move this to an earlier stage of processing, for example prior to adding the montage as you mentioned.

Another thing I see looking at the re-referencing code is that it assumes the user wants to re-reference to the average of all electrodes, the 'ref_channels' parameter is just used to indicate an old reference that needs to be added back as zeros. We should probably have the reference to use as a parameter to the function - either 'average' or the channel(s) to use.

**Comment by yanbin-niu** [comment]
@DMRoberts Thank you Dan! I also noticed the problems you mentioned, so I raised this issue while I was trying to fix these. So, I think there are two places that need to be modified: 
1) we add the reference back if needed prior to adding the montage;
2) modify the current re-reference feature, so it receives 'average' or channel(s) that the user specifies.

Do you see any potential issue if we add the reference back at the earliest stage? @DMRoberts

**Comment by DMRoberts** [comment]
> Do you see any potential issue if we add the reference back at the earliest stage? @DMRoberts

@yanbin-niu I don't think so. I believe the CMI dataset we have been using for testing so far also has the reference channel included as 0s.

**Comment by yanbin-niu** [comment]
@DMRoberts Great! Thank you Dan!!
