### ISSUE TITLE
The docker container is missing some of mne dependencies

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#38]
After rolling back to the old requirement.txt, the docker container is currently missing some of mne dependencies.
![image](https://user-images.githubusercontent.com/79607547/114573139-b16cc100-9caa-11eb-969a-8f35099612cf.png)

**Comment by F-said** [comment]
Potential fix in PR #39 . Continuing to research fix that won't require image rebuild as well as combine pip installs of `dockerfile ` and `requirements.txt`

**Comment by georgebuzzell** [comment]
Hey @F-said thank you for taking a stab at this! Let me know if I can help provide clarity around the github workflow. Long story short is that "main" essentially has nothing useful right now."Dev" is the most developed branch right now. When doin work on a particular feature, you should branch off from "dev" into dev-[featureName]. You then push any incremental code to a further branch ending in your name. The purpose of the branch with your own name is to have a branch with direct push access (all others require a pull request and review). Here are further reminders from the readme. Happy to discuss on a call though!

Reminders:

only push directly (without code review) to dev-feature-[featureName]=[yourName]
Must initiate pull request (and assign at least one person) for any higher-level branch
Mandatory code review by one person for all pull requests
main should be 100% stable and deployable/usable by any lab member (i.e. must also have full documentation and no "test features")
dev is the must up-to-date, complete version of the code, including all tested features, though dev is considered alpha/beta
dev-feature-[featureName] reflects a branch devoted to development/testing of a particular feature. Likely not stable, but at least has been reviewed by a second author

**Comment by georgebuzzell** [comment]
@yanbin-niu and @F-said I notice that you too are both assigned here. Are you all in communication about this issue? Just want to make sure no redoubling of efforts. :)

**Comment by yanbin-niu** [comment]
@georgebuzzell I got this this morning and will definitely communicate with Farukh.

**Comment by Jonhas** [comment]
@yanbin-niu I was taking a look at this since I was getting the same error. This seems to be an issue from matplotlib's side, It was an ongoing issue located https://github.com/matplotlib/matplotlib/issues/11929. 
There seems to be a solution, involving installing python-pyqt5 and qtcreator. Only issue is that this can take up to 250 mb to 1250 mb of space, given if you need to install any additional dependencies.

**Comment by yanbin-niu** [comment]
@Jonhas Did you get the exact same issue reporting "Failed to import any qt binding'? I think maybe you, Farukh and me can set up a real quick meeting tomorrow (anytime before 2pm-est), since now I was thinking if we stick to pip, the whole MNE dependencies might turn out to be a big issue as we move on and use more MNE functions. When I tried to include packages, it constantly threw out ERROR, something like 

"ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
#10 1020.9     tensorflow==2.4.1 from https://files.pythonhosted.org/packages/ac/9b/3fdbce9195fe53adbab1a930ee95a957af18c34a83ae5b1145f3cf8da409/tensorflow-2.4.1-cp38-cp38-manylinux2010_x86_64.whl#sha256=efa9daa4b3701a4e439b24b74c1e4b66844aee8ae5263fb3cc12281ac9cc9f67 (from -r requirements.txt (line 100)):"

I think it's because pip and conda are slightly different. (docker image build file uses pip and MNE official install guide use conda, where I get the dependencies that we should include. I included packages by checking its version in my anaconda).

Ideally, I personally prefer to use conda which is mne used, and I assume it will solve the problem once for all. But the downside is that we need to tweak image build file rather than simply edit requirements.txt. (I got some preliminary thoughts on this, and happy to hear you guys' suggestions/ insights)

**Comment by Jonhas** [comment]
@yanbin-niu I did get the same exact issue and installing those packages I mentioned fixed that error. However, it didn't take long for me to get another runtime error because of missing packages. Unfortunately, I would not be available until Friday 9 CDT, which is when we usually meet up, due to finals and other events. Regardless, I completely agree that its probably for the best to move on from pip to anaconda. Even though it is more complicated to tweak the image build file rather than editing a requirements.txt, it saves time on fixing import issues. I personally use conda on my host machine for it automatically includes all dependencies that a package needs and is very simple to use.

**Comment by yanbin-niu** [comment]
@Jonhas Exactly! That is what I have experienced -- after fixing an issue, another one popped up. But, no worries about this right now and please prioritize your finals (Good luck!!)

**Comment by georgebuzzell** [comment]
@yanbin-niu and @Jonhas Really glad you all suggest the move from Pip to Conda! @DMRoberts and I were actually suggesting this for the docker for other reasons the other day. 

In short, I would be 100% in favor of overhauling the docker we all use to rely on conda instead of Pip. If anyone feels comfortable taking a stab at this, please do! @yanbin-niu I think you said you might do this?

@F-said

**Comment by yanbin-niu** [comment]
@georgebuzzell @Jonhas @DMRoberts @F-said 
Last problem I am having is:

when we use notebook on our local pc, and "matplotlib.use('Qt5Agg')" will help plot in a new window (when we `raw.plot()`).

it seems we can not do this in the container?
https://stackoverflow.com/questions/56129786/cannot-load-backend-qt5agg-which-requires-the-qt5-interactive-framework-as

> This is happening because Google Colab and Jupyter run on virtual environments which do not support GUI outputs as you cannot open new windows through a browser.
> 
> Running it locally on a code editor(Spyder, or even IDLE) ensures that it can open a new window for the GUI to initialize.
> 
> For coding the GUI it is best to do it locally on a full-fledged code editor.

Any ideas on this? should we just not use matplotlib.use('Qt5Agg')?

**Comment by F-said** [comment]
@yanbin-niu as a temporary measure I replaced `matplotlib.use('Qt5Agg')` with `%matplotlib inline` to output graphs. Is `pyqt` a hard requirement for the pipeline @georgebuzzell  ?

**Comment by georgebuzzell** [comment]
First, thank you, @yanbin-niu and @F-said for your work on this! Great figuring out the exact issue here, @yanbin-niu and creative workaround, @F-said.

That said, it seems like this might be a (another) reason to drop Jupyter, actually. We were using Jupyter because some people do seem to like using it for development (though not everyone). If Jupyter has crucial issues with opening a GUI, that seems like a good reason to drop Jupyter and move to just using an IDE.

@Jonhas @DMRoberts @F-said @yanbin-niu As individuals that have been making heavy contributions so far, what are all of your feelings on dropping Jupyter vs trying to make it work. We could perhaps find a workaround (e.g. @F-said's suggestion), however, my thinking is that Jupyter is going to keep causing issues, and it Jupyter will not even be part of the final pipeline and/or regular use. Can we maybe get a vote here? I think that @CamachoBry and @kiaraafarias should also vote, as they have been using Jupyter for another project in the lab. 

So, @Jonhas @DMRoberts @F-said @yanbin-niu @CamachoBry and @kiaraafarias: who is OK with dropping Jupyter support and who would prefer to try to find ways to make it work?

**Comment by georgebuzzell** [comment]
Just to be clear: ANYONE should feel free to vote! We of course welcome any/all opinons. I only listed those that have been making more of the contributions in base EEG so far, as well as two people that I know, are continuing with efforts currently in another project that was at least initially using Jupyter.

**Comment by Jonhas** [comment]
@F-said PyQt is a dependency for a lot of plotting functionality. Essentially, Pyqt is a python bindings for the Qt cross-platform C++ framework, widget toolkit for creating graphical user interfaces, which was the cause of this issue to begin with. it's pretty wonky with jupyter notebook and sometimes wouldn't work. With regards to that, @georgebuzzell I am in favor of dropping jupyter notebooks support and working with your favorite text editor or IDE such as vim or PyCharm.

**Comment by georgebuzzell** [comment]
Based on slack discussion, it sounds like we might try continuing to support Jupyter and .py. However, that is also dependent on how viable converting to/from .py and ..ipynb is, based on the other other issue you are working on @Jonhas 

The current, working plan (very subject to change) is:

Developers can use either .py and an IDE or Jupyter for development, with the caveat that ALL tests must be run in the Dockerfile before a PR, and that Jupypter cannot be used when developing interactive features. Also, the general understanding will be that the PREFERRED development environment is .py and an IDE, with Jupyter also supported only to allow more flexibility in terms of developer preferences.

@F-said @Jonhas @yanbin-niu @DMRoberts comments/thoughts on the working plan above?

**Comment by F-said** [comment]
@georgebuzzell IMO switching over to .py files for development could also help with plans for automated testing, where commits would be checked against an automated tester to see if data-set preconditions or the BIDS format were violated.

**Comment by georgebuzzell** [comment]
@F-said good point, though @yanbin-niu set up the CI to automatically convert .ipynb to .py (temporarily on the github server) for testing compliance with pep8 (via flake8); I would assume something similar would work for jupyter? 

But still, I agree, @F-said that the preferred method should be .py, and that perhaps we even require PRs to include a .py file to make this all easier? That is, someone can always work with jupyter nb on local, and convert the repo .py files to .ipynb, but perhaps we should require conversion and testing to .py before submitting a PR?

Thoughts on this? @F-said @DMRoberts @Jonhas @yanbin-niu @stevenwtolbert ?
