### ISSUE TITLE
launching docker container and mounting volume

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#43]
Modify docker readme to include proper instructions for creating and mounting a volume. Currently, we are using bind mounts (not what we want).

See:
#36

**Comment by Jonhas** [comment]
@georgebuzzell This is what I have written. please let me know if this works for you with the new docker file @yanbin-niu made. If it works fine, I will make a pull request to update the README. It goes as follows: 

With a docker file and any additional files, such as a requirements.txt or environment.yml, we can construct a docker container with a volume attached to it in the following way. Let us begin by building the docker file with a tag called anaconda. So, we do
`docker build -t [tag]` 
where:
- docker build command builds docker images from a Dockerfile
- t flag tags our image. This of this simply as a human-readable name for the final image.
- .  tells that docker should look for the Dockerfile in the current directory

 Now, Let us create a volume called data. To create the volume, we run
` docker volume create data `
When we run `docker volume ls`, we should get the following output: 
```bash
DRIVER    VOLUME NAME
local     data
```
which lists all of the volumes known to docker. 

If we want to see detailed information on the docker container, we can use the inspect command. So, we do 
`docker inspect data `
producing the following output:
```json
[
    {
        "CreatedAt": "2021-04-17T03:53:57Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/data/_data",
        "Name": "data",
        "Options": {},
        "Scope": "local"
    }
]
```
To mount a data volume to a container, we add the --mount flag to the docker run command. It adds the volume 
to the specified container, where it stores the data produced inside the virtual environment. To run a container 
and mount a data volume to it, while routing it to to some port, such as port 5000, we use the following syntax: 
```bash
docker run --name=[containerName] -it -w /projects -p 5000:8888 --mount source=[volume_name], destination=[docker_image] anaconda
```
Therefore, for this example, to launch the container and mount the data volume to it, we run 
```bash
docker run --name=mini -it -w /projects -p 5000:8888 --mount source=data,destination=/home/ubuntu/data anaconda 
```

Which will now construct a new container on port 5000 and with a volume attached to it, mounted on /home/ubuntu/data.

**Comment by yanbin-niu** [comment]
@Jonhas With old bind mounts, `docker run` will copy everything from $(PWD) into container, so we can run code and use the data. However, with volume mounts, it is different. So, now one thing I did not figure out is, how we put scripts and raw data into, say `data volume`? since technically speaking, this volume can not be manipulated by the processes other than docker. I was thinking about this early on and I guess maybe we can git clone the script in the container? but how about raw data? 
Happy to learn your insights!

**Comment by georgebuzzell** [comment]
@Jonhas what you have looks GREAT! Thank you! Please do a PR. 

@yanbin-niu please also move forward with a PR for the docker file and yaml. Awesome work, thank you!

@Jonhas curious as well about getting the data into the volume mount. I know this must be possible. Is one way maybe to create a volume mount, then, also create a bind mount, and to copy the data from the bind mount to the volume mount? Relatedly, I assume we would need to move data back from the volume to the bind mount to write out to local from the container? @yanbin-niu @DMRoberts and @F-said comments welcome here as well!!

**Comment by DMRoberts** [comment]
@yanbin-niu @georgebuzzell Once the volume is attached to the container, you can use Docker `cp` command to copy data from the host to the container (or vice versa). I believe this had to be done from the host side (not from within the container) as I don't think the docker command works from inside the container.

So for example if you have a container named 'mini' with an attached volume as in Yanbin's example above, running the following from the host where the data is stored:

 docker cp HBN_R2_1_Pheno.csv mini:/home/ubuntu/data
 
 Would copy the file HBN_R2_1_Pheno.csv from the host to the '/home/ubuntu/data' directory on the container 'mini'. 
 
I think this would only need to be done once, since the data should persist on the volume even after the container is stopped. I don't think the container needs to be running when the data is transferred, either.

**Comment by Jonhas** [comment]
@georgebuzzell @yanbin-niu I was just about to say this. Thank you for the Input @DMRoberts! Dan is correct, docker cp is only done once from the host side, and does a copy from the host machine to the docker container. Similarly, we can do copies from the docker container onto the host machine. This is actually how I've been working. For example, with regards to the eeg_matchingpennies dataset, one would do
```vim
docker cp "C:\users\jonhas\downloads\eeg_matchingPennies" eeg:"/home/ubuntu/"
```
which follows the following syntax:
` docker cp <src-path> <container>:<dest-path> `
where the pathway can be the full path to where the data is located, say in "C:\users\[name]\downloads\data", whichever container tag, and the destination path being the volume location.  I'll make sure to add this to the README.

**Comment by yanbin-niu** [comment]
@DMRoberts @Jonhas Thank you so much for the detailed and clear explanation!! So happy to have opportunity to get involved in the team and constantly learn from you guys!!

**Comment by georgebuzzell** [comment]
@DMRoberts @Jonhas @yanbin-niu Thank you, to all of you! This is very simple and clear now!

@Jonhas Please do go ahead with your PR mentioned above, with the added details of copying data into/out of the volume in the readme for the docker.
