### ISSUE TITLE
Add CI actions to auto-test for Pep8 complicance

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/baseEEG#62]
@yanbin-niu if you think it is ready, can you please add the CI code for this repo, as well as please link to the documentation you wrote on drive?

@F-said After @yanbin-niu adds the CI code, and links to the doc she wrote on the roadmap readme, can you please  add the CI documentation that @yanbin-niu created to the wiki, and then update the roadmap link to link to the wiki, instead of drive?

**Comment by yanbin-niu** [comment]
@georgebuzzell 

The CI has to be set up in each branch (All of sudden, I understand the CI fork issue that I mentioned before). I just tried in my feature-reref branch (I need some python code to do the testing). For me, it looks good. You can see that in PR:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/79607547/115989696-2799ed80-a5f2-11eb-91de-a3064e5583c0.png">
means the script didnot pass the pylint…(I can fix this later with my code)

When you review the PR, you can also see the CI results:
![image](https://user-images.githubusercontent.com/79607547/115989744-6a5bc580-a5f2-11eb-9a6e-a7ceb3e6c134.png)

If you approve my PR (I think you can still approve it even the previous code did not pass the CI test), the CI will be merged into dev-feature-reref brach. So, let me know, which branch do we need CI testing. I think, it may be good to start with dev branch. Afterwards, when people branch off from dev, they will have this CI testing as well.

If you agree and want me to set this CI up in the dev branch, you will not see any error for now, since our current dev branch does not have any python code. I will keep the PR for the dev-feature-reref brach open, just in case you want to see how it looks like. Feel free to close or reject it, if you agree that I should set the CI up in the dev branch. Then I will make a new PR to the dev branch.

**Comment by yanbin-niu** [comment]
@georgebuzzell A point related to your last comment in #38 . I did not include doing pylint for .ipynb in the PR, since I assume that we agree upon only pushing .py files into our repo?

Let me know if you change your mind or you want me to include doing pylint for .ipynb as well.

**Comment by georgebuzzell** [comment]
@yanbin-niu this is wonderful!!

Yes, no need to include the conversion of .ipynb in the ci right now. The current plan is to only push .py files, as you stated. We might change that in the future, but no need to worry about it for now!

@F-said I just looked voer the code and made a minor change. Can you please also review @yanbin-niu 's PR and then merge in if you agree? If so, please also do a PR for Dev and Main. 

@F-said and @yanbin-niu please see my additional comments on the PR here: https://github.com/NDCLab/baseEEG/pull/64#issuecomment-826313057

Thank you, both!!

**Comment by yanbin-niu** [comment]
I just realized I forgot to include the documentation link. I edited the documentation a little. It would be great if @georgebuzzell and @F-said can do a final review. https://docs.google.com/document/d/1lTYCLn6XK4Ln-BjcNhMMqpQFhYWg6OHB/edit

@georgebuzzell do you want me to add a separate readme in the same folder or just add a link into the roadmap readme?

**Comment by georgebuzzell** [comment]
Thanks, @yanbin-niu! I think just adding a link in the roadmap readme is fine for now. can you please make a pr for that?

@F-said please take a look at the ci documentation when you have a chance!

**Comment by F-said** [comment]
PR'd linter into dev-reref.

PR'd README to dev.

To get the linter into dev & main, it looks like the re-reference function would also need a code review. Whenever this function is ready @yanbin-niu , feel free to make a PR into dev. 

Safe to close? @georgebuzzell

**Comment by yanbin-niu** [comment]
@F-said I will make a PR to dev, just include CI.

**Comment by F-said** [comment]
Thanks @yanbin-niu ! Missed your comment here:

> If you agree and want me to set this CI up in the dev branch, you will not see any error for now, since our current dev branch does not have any python code. I will keep the PR for the dev-feature-reref brach open, just in case you want to see how it looks like. Feel free to close or reject it, if you agree that I should set the CI up in the dev branch. Then I will make a new PR to the dev branch.

Let me know if I should undo the changes the PR made to the reref branch.

**Comment by yanbin-niu** [comment]
@F-said Not at all! Actually it’s my bad, should have communicated this more clearly! thank you!!
