### ISSUE TITLE
A runtime warning for annotations expanding outside the range

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#68]
While reading the BIDS file, there was a runtime warning:

> RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
> raw = mne_bids.read_raw_bids(bids_path)

**Comment by Jonhas** [comment]
@yanbin-niu Can I ask what you did previously that may have prompted this issue? Are you possibly trying to concatenate annotations or cropping the data? I ask since that runtime error shows up when using the crop function, which remove all annotation that are outside of [tmin, tmax]. From the warning, it seems we limited one annotation while we read from BIDS.

**Comment by yanbin-niu** [comment]
@Jonhas Thanks for the comments! what I did was:

```
bids_root = pathlib.Path('BIDS')
bids_path = mne_bids.BIDSPath(subject='NDARAB793GL3',
                              session='01',
                              task='ContrastChangeBlock1',
                              run='01',
                              datatype='eeg',
                              root=bids_root)
raw = mne_bids.read_raw_bids(bids_path)
```

I think in feature-io @DMRoberts  did crop the data and saved the data of each event into BIDS.

**Comment by DMRoberts** [comment]
I looked into this a little bit, there seems to be the same number of annotations (73) in the .tsv file as are being loaded with the data:

```
import pathlib
import mne_bids
import pandas as pd

bids_root = pathlib.Path('BIDS')
bids_path = mne_bids.BIDSPath(subject='NDARAB793GL3',
                              session='01',
                              task='ContrastChangeBlock1',
                              run='01',
                              datatype='eeg',
                              root=bids_root)
raw = mne_bids.read_raw_bids(bids_path)

print('Number Events in Loaded Data = {}'.format(len(raw.annotations)))

events_data = pd.read_csv('BIDS/sub-NDARAB793GL3/ses-01/eeg/sub-NDARAB793GL3_ses-01_task-ContrastChangeBlock1_run-01_events.tsv', delimiter='\t')
print('Number Events in events.tsv = {}'.format(len(events_data)))

```

I think despite having the correct number of annotations, warning might be related to the last annotation / event, being in the last sample of the recording. While I don't think that should generally be a problem, I think our cropped recordings may each be 1 sample too long, where they are capturing the event that indicates the start of the next block. I'm looking to see if there might be a mistake with my logic converting from samples to time, where I had made each cropped recording 1 sample longer than they should be.

**Comment by DMRoberts** [comment]
Ok I just refactored my logic to avoid the manual conversion from samples to times, but the problem remains. I think when I crop the data in MNE, is it cropping to the correct end-time but not cropping out the events correctly. So for example say want to crop up to but not including 5 minutes (because the marker for the next block occurs at 5 minutes). The data will be from 0 to 4.998 seconds, but it will retain the event that occurred at 5 minutes within the data. I think those final stray events are what is generating the warning. For example see in the following output that the final data sample of one of our cropped files is at 770.382 seconds, but the final annotation (the 'onset') is at 770.384 seconds.

```
<RawBrainVision | sub-NDARAB793GL3_ses-01_task-RestingState_run-01_eeg.eeg, 129 x 385192 (770.4 s), ~181 kB, data not loaded>
data.times[-1]
770.382
data.annotations[-1]
OrderedDict([('onset', 770.384), ('duration', 0.0), ('description', '91'), ('orig_time', datetime.datetime(2017, 5, 12, 15, 7, 18, tzinfo=datetime.timezone.utc))])
```

 I'll look more into this to see if this is something I'm doing wrong or potentially a bug in MNE.

**Comment by DMRoberts** [comment]
Ok, I think there may actually be a bug in either MNE's cropping behavior, or the way mne-bids exports the files, though I think it is probably the former. I created a test script as a Gist if anyone else wants to check it out: 

https://gist.github.com/DMRoberts/7c3b997825148b21c3857ef0adbe5e3e

Basically it seems that when cropping the data, annotations that exist 1 sample beyond the crop region aren't being cropped out properly. MNE doesn't complain about this if you save and then reload the file, but saving and reloading as a BIDS formatted dataset generates the warning on load.

**Comment by Jonhas** [comment]
@DMRoberts I took a look at your script and I tested it. From this, we see that the annotation that occurs at tmax is retained, where in the test script case, it was 20. This could simply be how crop() is defined while approximating. Within this example, If we were to run, 
```python3
for x in cropped_data_false.times:
    print(x)
```
We would get a list of times, with each iteration following a two of a thousandth. We see that the last time is 19.998 which is expected, since we are not including tmax. However, we see that the annotation at 20 is retained, It is possible when we are cropping the data, the new annotations are within some domain, from some delta < x <= tmax. When we perform the crop function on the raw object, it also calls the set annotations functions. When reading the set annotations function, we see:
```python3
            delta = 1. / self.info['sfreq']
            new_annotations = annotations.copy()
            new_annotations._prune_ch_names(self.info, on_missing)
            if annotations.orig_time is None:
                new_annotations.crop(0, self.times[-1] + delta,
                                     emit_warning=emit_warning)
                new_annotations.onset += self._first_time
            else:
                tmin = meas_date + timedelta(0, self._first_time)
                tmax = tmin + timedelta(seconds=self.times[-1] + delta)
                new_annotations.crop(tmin=tmin, tmax=tmax,
                                     emit_warning=emit_warning)
                new_annotations.onset -= (
                    meas_date - new_annotations.orig_time).total_seconds()
            new_annotations._orig_time = meas_date

            self._annotations = new_annotations
    return self 
```
which could be a reason why we see that when cropping the data, annotations that exist 1 sample beyond the crop region aren't being cropped out properly.

**Comment by georgebuzzell** [comment]
@DMRoberts will:

1. modify feature-io to crop at next annotation marker -2 samples so that the extra annotation is not pulled in. 
2. Will then do a new PR. Assign @Jonhas or @F-said 
3. @DMRoberts will also post an issue for this on men gh and link to that issue here.

**Comment by DMRoberts** [comment]
The pull request to reduce segment length by 1 sample to avoid the extra annotation is here: https://github.com/NDCLab/baseEEG/pull/90

It might be best to leave the issue open until we finish following up with MNE about the potential that this is a bug.

**Comment by F-said** [comment]
leaving open, tagging as "wontfix" for organization

**Comment by DMRoberts** [comment]
I filed an issue with MNE about this potential bug: https://github.com/mne-tools/mne-python/issues/9383

The runtime warning as been resolved with merged PR https://github.com/NDCLab/baseEEG/pull/90
